#pragma once

#ifndef _ENUM_H_
#define _ENUM_H_

#define GET_MACRO(_1,_2,_3,_4,_5,_6,_7,_8,_9,_10,_11,_12,_13,_14,_15,_16,_17,_18,_19,_20,_21,_22,_23,_24,_25,_26,_27,_28,_29,_30,_31,_32,_33,_34,_35,_36,_37,_38,_39,_40,_41,_42,_43,_44,_45,_46,_47,_48,_49,_50,_51,_52,_53,_54,_55,_56,_57,_58,_59,_60,_61,_62,_63,_64,_65,_66,_67,_68,_69,_70,_71,_72,_73,_74,_75,_76,_77,_78,_79,_80,_81,_82,_83,_84,_85,_86,_87,_88,_89,_90,_91,_92,_93,_94,_95,_96,_97,_98,_99,_100,NAME,...) NAME 

#define __FE_1(WHAT, X) WHAT(X) 
#define __FE_2(WHAT, X, ...) WHAT(X)__FE_1(WHAT, __VA_ARGS__)
#define __FE_3(WHAT, X, ...) WHAT(X)__FE_2(WHAT, __VA_ARGS__)
#define __FE_4(WHAT, X, ...) WHAT(X)__FE_3(WHAT, __VA_ARGS__)
#define __FE_5(WHAT, X, ...) WHAT(X)__FE_4(WHAT, __VA_ARGS__)
#define __FE_6(WHAT, X, ...) WHAT(X)__FE_5(WHAT, __VA_ARGS__)
#define __FE_7(WHAT, X, ...) WHAT(X)__FE_6(WHAT, __VA_ARGS__)
#define __FE_7(WHAT, X, ...) WHAT(X)__FE_6(WHAT, __VA_ARGS__)
#define __FE_8(WHAT, X, ...) WHAT(X)__FE_7(WHAT, __VA_ARGS__)
#define __FE_9(WHAT, X, ...) WHAT(X)__FE_8(WHAT, __VA_ARGS__)
#define __FE_10(WHAT, X, ...) WHAT(X)__FE_9(WHAT, __VA_ARGS__)
#define __FE_11(WHAT, X, ...) WHAT(X)__FE_10(WHAT, __VA_ARGS__)
#define __FE_12(WHAT, X, ...) WHAT(X)__FE_11(WHAT, __VA_ARGS__)
#define __FE_13(WHAT, X, ...) WHAT(X)__FE_12(WHAT, __VA_ARGS__)
#define __FE_14(WHAT, X, ...) WHAT(X)__FE_13(WHAT, __VA_ARGS__)
#define __FE_15(WHAT, X, ...) WHAT(X)__FE_14(WHAT, __VA_ARGS__)
#define __FE_16(WHAT, X, ...) WHAT(X)__FE_15(WHAT, __VA_ARGS__)
#define __FE_17(WHAT, X, ...) WHAT(X)__FE_16(WHAT, __VA_ARGS__)
#define __FE_18(WHAT, X, ...) WHAT(X)__FE_17(WHAT, __VA_ARGS__)
#define __FE_19(WHAT, X, ...) WHAT(X)__FE_18(WHAT, __VA_ARGS__)
#define __FE_20(WHAT, X, ...) WHAT(X)__FE_19(WHAT, __VA_ARGS__)
#define __FE_21(WHAT, X, ...) WHAT(X)__FE_20(WHAT, __VA_ARGS__)
#define __FE_22(WHAT, X, ...) WHAT(X)__FE_21(WHAT, __VA_ARGS__)
#define __FE_23(WHAT, X, ...) WHAT(X)__FE_22(WHAT, __VA_ARGS__)
#define __FE_24(WHAT, X, ...) WHAT(X)__FE_23(WHAT, __VA_ARGS__)
#define __FE_25(WHAT, X, ...) WHAT(X)__FE_24(WHAT, __VA_ARGS__)
#define __FE_26(WHAT, X, ...) WHAT(X)__FE_25(WHAT, __VA_ARGS__)
#define __FE_27(WHAT, X, ...) WHAT(X)__FE_26(WHAT, __VA_ARGS__)
#define __FE_28(WHAT, X, ...) WHAT(X)__FE_27(WHAT, __VA_ARGS__)
#define __FE_29(WHAT, X, ...) WHAT(X)__FE_28(WHAT, __VA_ARGS__)
#define __FE_30(WHAT, X, ...) WHAT(X)__FE_29(WHAT, __VA_ARGS__)
#define __FE_31(WHAT, X, ...) WHAT(X)__FE_30(WHAT, __VA_ARGS__)
#define __FE_32(WHAT, X, ...) WHAT(X)__FE_31(WHAT, __VA_ARGS__)
#define __FE_33(WHAT, X, ...) WHAT(X)__FE_32(WHAT, __VA_ARGS__)
#define __FE_34(WHAT, X, ...) WHAT(X)__FE_33(WHAT, __VA_ARGS__)
#define __FE_35(WHAT, X, ...) WHAT(X)__FE_34(WHAT, __VA_ARGS__)
#define __FE_36(WHAT, X, ...) WHAT(X)__FE_35(WHAT, __VA_ARGS__)
#define __FE_37(WHAT, X, ...) WHAT(X)__FE_36(WHAT, __VA_ARGS__)
#define __FE_38(WHAT, X, ...) WHAT(X)__FE_37(WHAT, __VA_ARGS__)
#define __FE_39(WHAT, X, ...) WHAT(X)__FE_38(WHAT, __VA_ARGS__)
#define __FE_40(WHAT, X, ...) WHAT(X)__FE_39(WHAT, __VA_ARGS__)
#define __FE_41(WHAT, X, ...) WHAT(X)__FE_40(WHAT, __VA_ARGS__)
#define __FE_42(WHAT, X, ...) WHAT(X)__FE_41(WHAT, __VA_ARGS__)
#define __FE_43(WHAT, X, ...) WHAT(X)__FE_42(WHAT, __VA_ARGS__)
#define __FE_44(WHAT, X, ...) WHAT(X)__FE_43(WHAT, __VA_ARGS__)
#define __FE_45(WHAT, X, ...) WHAT(X)__FE_44(WHAT, __VA_ARGS__)
#define __FE_46(WHAT, X, ...) WHAT(X)__FE_45(WHAT, __VA_ARGS__)
#define __FE_47(WHAT, X, ...) WHAT(X)__FE_46(WHAT, __VA_ARGS__)
#define __FE_48(WHAT, X, ...) WHAT(X)__FE_47(WHAT, __VA_ARGS__)
#define __FE_49(WHAT, X, ...) WHAT(X)__FE_48(WHAT, __VA_ARGS__)
#define __FE_50(WHAT, X, ...) WHAT(X)__FE_49(WHAT, __VA_ARGS__)
#define __FE_51(WHAT, X, ...) WHAT(X)__FE_50(WHAT, __VA_ARGS__)
#define __FE_52(WHAT, X, ...) WHAT(X)__FE_51(WHAT, __VA_ARGS__)
#define __FE_53(WHAT, X, ...) WHAT(X)__FE_52(WHAT, __VA_ARGS__)
#define __FE_54(WHAT, X, ...) WHAT(X)__FE_53(WHAT, __VA_ARGS__)
#define __FE_55(WHAT, X, ...) WHAT(X)__FE_54(WHAT, __VA_ARGS__)
#define __FE_56(WHAT, X, ...) WHAT(X)__FE_55(WHAT, __VA_ARGS__)
#define __FE_57(WHAT, X, ...) WHAT(X)__FE_56(WHAT, __VA_ARGS__)
#define __FE_58(WHAT, X, ...) WHAT(X)__FE_57(WHAT, __VA_ARGS__)
#define __FE_59(WHAT, X, ...) WHAT(X)__FE_58(WHAT, __VA_ARGS__)
#define __FE_60(WHAT, X, ...) WHAT(X)__FE_59(WHAT, __VA_ARGS__)
#define __FE_61(WHAT, X, ...) WHAT(X)__FE_60(WHAT, __VA_ARGS__)
#define __FE_62(WHAT, X, ...) WHAT(X)__FE_61(WHAT, __VA_ARGS__)
#define __FE_63(WHAT, X, ...) WHAT(X)__FE_62(WHAT, __VA_ARGS__)
#define __FE_64(WHAT, X, ...) WHAT(X)__FE_63(WHAT, __VA_ARGS__)
#define __FE_65(WHAT, X, ...) WHAT(X)__FE_64(WHAT, __VA_ARGS__)
#define __FE_66(WHAT, X, ...) WHAT(X)__FE_65(WHAT, __VA_ARGS__)
#define __FE_67(WHAT, X, ...) WHAT(X)__FE_66(WHAT, __VA_ARGS__)
#define __FE_68(WHAT, X, ...) WHAT(X)__FE_67(WHAT, __VA_ARGS__)
#define __FE_69(WHAT, X, ...) WHAT(X)__FE_68(WHAT, __VA_ARGS__)
#define __FE_70(WHAT, X, ...) WHAT(X)__FE_69(WHAT, __VA_ARGS__)
#define __FE_71(WHAT, X, ...) WHAT(X)__FE_70(WHAT, __VA_ARGS__)
#define __FE_72(WHAT, X, ...) WHAT(X)__FE_71(WHAT, __VA_ARGS__)
#define __FE_73(WHAT, X, ...) WHAT(X)__FE_72(WHAT, __VA_ARGS__)
#define __FE_74(WHAT, X, ...) WHAT(X)__FE_73(WHAT, __VA_ARGS__)
#define __FE_75(WHAT, X, ...) WHAT(X)__FE_74(WHAT, __VA_ARGS__)
#define __FE_76(WHAT, X, ...) WHAT(X)__FE_75(WHAT, __VA_ARGS__)
#define __FE_77(WHAT, X, ...) WHAT(X)__FE_76(WHAT, __VA_ARGS__)
#define __FE_78(WHAT, X, ...) WHAT(X)__FE_77(WHAT, __VA_ARGS__)
#define __FE_79(WHAT, X, ...) WHAT(X)__FE_78(WHAT, __VA_ARGS__)
#define __FE_80(WHAT, X, ...) WHAT(X)__FE_79(WHAT, __VA_ARGS__)
#define __FE_81(WHAT, X, ...) WHAT(X)__FE_80(WHAT, __VA_ARGS__)
#define __FE_82(WHAT, X, ...) WHAT(X)__FE_81(WHAT, __VA_ARGS__)
#define __FE_83(WHAT, X, ...) WHAT(X)__FE_82(WHAT, __VA_ARGS__)
#define __FE_84(WHAT, X, ...) WHAT(X)__FE_83(WHAT, __VA_ARGS__)
#define __FE_85(WHAT, X, ...) WHAT(X)__FE_84(WHAT, __VA_ARGS__)
#define __FE_86(WHAT, X, ...) WHAT(X)__FE_85(WHAT, __VA_ARGS__)
#define __FE_87(WHAT, X, ...) WHAT(X)__FE_86(WHAT, __VA_ARGS__)
#define __FE_88(WHAT, X, ...) WHAT(X)__FE_87(WHAT, __VA_ARGS__)
#define __FE_89(WHAT, X, ...) WHAT(X)__FE_88(WHAT, __VA_ARGS__)
#define __FE_90(WHAT, X, ...) WHAT(X)__FE_89(WHAT, __VA_ARGS__)
#define __FE_91(WHAT, X, ...) WHAT(X)__FE_90(WHAT, __VA_ARGS__)
#define __FE_92(WHAT, X, ...) WHAT(X)__FE_91(WHAT, __VA_ARGS__)
#define __FE_93(WHAT, X, ...) WHAT(X)__FE_92(WHAT, __VA_ARGS__)
#define __FE_94(WHAT, X, ...) WHAT(X)__FE_93(WHAT, __VA_ARGS__)
#define __FE_95(WHAT, X, ...) WHAT(X)__FE_94(WHAT, __VA_ARGS__)
#define __FE_96(WHAT, X, ...) WHAT(X)__FE_95(WHAT, __VA_ARGS__)
#define __FE_97(WHAT, X, ...) WHAT(X)__FE_96(WHAT, __VA_ARGS__)
#define __FE_98(WHAT, X, ...) WHAT(X)__FE_97(WHAT, __VA_ARGS__)
#define __FE_99(WHAT, X, ...) WHAT(X)__FE_98(WHAT, __VA_ARGS__)
#define __FE_100(WHAT, X, ...) WHAT(X)__FE_99(WHAT, __VA_ARGS__)

#define ENUM_STRING(name) #name,

#define __FOR_EACH(action,...) \
  GET_MACRO(__VA_ARGS__,__FE_100,__FE_99,__FE_98,__FE_97,__FE_96,__FE_95,__FE_94,__FE_93,__FE_92,__FE_91,__FE_90,__FE_89,__FE_88,__FE_87,__FE_86,__FE_85,__FE_84,__FE_83,__FE_82,__FE_81,__FE_80,__FE_79,__FE_78,__FE_77,__FE_76,__FE_75,__FE_74,__FE_73,__FE_72,__FE_71,__FE_70,__FE_69,__FE_68,__FE_67,__FE_66,__FE_65,__FE_64,__FE_63,__FE_62,__FE_61,__FE_60,__FE_59,__FE_58,__FE_57,__FE_56,__FE_55,__FE_54,__FE_53,__FE_52,__FE_51,__FE_50,__FE_49,__FE_48,__FE_47,__FE_46,__FE_45,__FE_44,__FE_43,__FE_42,__FE_41,__FE_40,__FE_39,__FE_38,__FE_37,__FE_36,__FE_35,__FE_34,__FE_33,__FE_32,__FE_31,__FE_30,__FE_29,__FE_28,__FE_27,__FE_26,__FE_25,__FE_24,__FE_23,__FE_22,__FE_21,__FE_20,__FE_19,__FE_18,__FE_17,__FE_16,__FE_15,__FE_14,__FE_13,__FE_12,__FE_11,__FE_10,__FE_9,__FE_8,__FE_7,__FE_6,__FE_5,__FE_4,__FE_3,__FE_2,__FE_1)(action,__VA_ARGS__)

#define ENUM(name, ...) typedef enum {__VA_ARGS__} name; \
                        static char* name##_STR[] = {__FOR_EACH(ENUM_STRING, __VA_ARGS__)}

#endif //_ENUM_H_ 
