#pragma once

#ifndef _ENUM_H_
#define _ENUM_H_

#define GET_MACRO(_1,_2,_3,_4,_5,_6,_7,_8,_9,_10,_11,_12,_13,_14,_15,_16,_17,_18,_19,_20,_21,_22,_23,_24,_25,_26,_27,_28,_29,_30,_31,_32,_33,_34,_35,_36,_37,_38,_39,_40,_41,_42,_43,_44,_45,_46,_47,_48,_49,_50,_51,_52,_53,_54,_55,_56,_57,_58,_59,_60,_61,_62,_63,_64,_65,_66,_67,_68,_69,_70,_71,_72,_73,_74,_75,_76,_77,_78,_79,_80,_81,_82,_83,_84,_85,_86,_87,_88,_89,_90,_91,_92,_93,_94,_95,_96,_97,_98,_99,_100,NAME,...) NAME 

#define FE_1__(WHAT, X) WHAT(X) 
#define FE_2__(WHAT, X, ...) WHAT(X)FE_1__(WHAT, __VA_ARGS__)
#define FE_3__(WHAT, X, ...) WHAT(X)FE_2__(WHAT, __VA_ARGS__)
#define FE_4__(WHAT, X, ...) WHAT(X)FE_3__(WHAT, __VA_ARGS__)
#define FE_5__(WHAT, X, ...) WHAT(X)FE_4__(WHAT, __VA_ARGS__)
#define FE_6__(WHAT, X, ...) WHAT(X)FE_5__(WHAT, __VA_ARGS__)
#define FE_7__(WHAT, X, ...) WHAT(X)FE_6__(WHAT, __VA_ARGS__)
#define FE_7__(WHAT, X, ...) WHAT(X)FE_6__(WHAT, __VA_ARGS__)
#define FE_8__(WHAT, X, ...) WHAT(X)FE_7__(WHAT, __VA_ARGS__)
#define FE_9__(WHAT, X, ...) WHAT(X)FE_8__(WHAT, __VA_ARGS__)
#define FE_10__(WHAT, X, ...) WHAT(X)FE_9__(WHAT, __VA_ARGS__)
#define FE_11__(WHAT, X, ...) WHAT(X)FE_10__(WHAT, __VA_ARGS__)
#define FE_12__(WHAT, X, ...) WHAT(X)FE_11__(WHAT, __VA_ARGS__)
#define FE_13__(WHAT, X, ...) WHAT(X)FE_12__(WHAT, __VA_ARGS__)
#define FE_14__(WHAT, X, ...) WHAT(X)FE_13__(WHAT, __VA_ARGS__)
#define FE_15__(WHAT, X, ...) WHAT(X)FE_14__(WHAT, __VA_ARGS__)
#define FE_16__(WHAT, X, ...) WHAT(X)FE_15__(WHAT, __VA_ARGS__)
#define FE_17__(WHAT, X, ...) WHAT(X)FE_16__(WHAT, __VA_ARGS__)
#define FE_18__(WHAT, X, ...) WHAT(X)FE_17__(WHAT, __VA_ARGS__)
#define FE_19__(WHAT, X, ...) WHAT(X)FE_18__(WHAT, __VA_ARGS__)
#define FE_20__(WHAT, X, ...) WHAT(X)FE_19__(WHAT, __VA_ARGS__)
#define FE_21__(WHAT, X, ...) WHAT(X)FE_20__(WHAT, __VA_ARGS__)
#define FE_22__(WHAT, X, ...) WHAT(X)FE_21__(WHAT, __VA_ARGS__)
#define FE_23__(WHAT, X, ...) WHAT(X)FE_22__(WHAT, __VA_ARGS__)
#define FE_24__(WHAT, X, ...) WHAT(X)FE_23__(WHAT, __VA_ARGS__)
#define FE_25__(WHAT, X, ...) WHAT(X)FE_24__(WHAT, __VA_ARGS__)
#define FE_26__(WHAT, X, ...) WHAT(X)FE_25__(WHAT, __VA_ARGS__)
#define FE_27__(WHAT, X, ...) WHAT(X)FE_26__(WHAT, __VA_ARGS__)
#define FE_28__(WHAT, X, ...) WHAT(X)FE_27__(WHAT, __VA_ARGS__)
#define FE_29__(WHAT, X, ...) WHAT(X)FE_28__(WHAT, __VA_ARGS__)
#define FE_30__(WHAT, X, ...) WHAT(X)FE_29__(WHAT, __VA_ARGS__)
#define FE_31__(WHAT, X, ...) WHAT(X)FE_30__(WHAT, __VA_ARGS__)
#define FE_32__(WHAT, X, ...) WHAT(X)FE_31__(WHAT, __VA_ARGS__)
#define FE_33__(WHAT, X, ...) WHAT(X)FE_32__(WHAT, __VA_ARGS__)
#define FE_34__(WHAT, X, ...) WHAT(X)FE_33__(WHAT, __VA_ARGS__)
#define FE_35__(WHAT, X, ...) WHAT(X)FE_34__(WHAT, __VA_ARGS__)
#define FE_36__(WHAT, X, ...) WHAT(X)FE_35__(WHAT, __VA_ARGS__)
#define FE_37__(WHAT, X, ...) WHAT(X)FE_36__(WHAT, __VA_ARGS__)
#define FE_38__(WHAT, X, ...) WHAT(X)FE_37__(WHAT, __VA_ARGS__)
#define FE_39__(WHAT, X, ...) WHAT(X)FE_38__(WHAT, __VA_ARGS__)
#define FE_40__(WHAT, X, ...) WHAT(X)FE_39__(WHAT, __VA_ARGS__)
#define FE_41__(WHAT, X, ...) WHAT(X)FE_40__(WHAT, __VA_ARGS__)
#define FE_42__(WHAT, X, ...) WHAT(X)FE_41__(WHAT, __VA_ARGS__)
#define FE_43__(WHAT, X, ...) WHAT(X)FE_42__(WHAT, __VA_ARGS__)
#define FE_44__(WHAT, X, ...) WHAT(X)FE_43__(WHAT, __VA_ARGS__)
#define FE_45__(WHAT, X, ...) WHAT(X)FE_44__(WHAT, __VA_ARGS__)
#define FE_46__(WHAT, X, ...) WHAT(X)FE_45__(WHAT, __VA_ARGS__)
#define FE_47__(WHAT, X, ...) WHAT(X)FE_46__(WHAT, __VA_ARGS__)
#define FE_48__(WHAT, X, ...) WHAT(X)FE_47__(WHAT, __VA_ARGS__)
#define FE_49__(WHAT, X, ...) WHAT(X)FE_48__(WHAT, __VA_ARGS__)
#define FE_50__(WHAT, X, ...) WHAT(X)FE_49__(WHAT, __VA_ARGS__)
#define FE_51__(WHAT, X, ...) WHAT(X)FE_50__(WHAT, __VA_ARGS__)
#define FE_52__(WHAT, X, ...) WHAT(X)FE_51__(WHAT, __VA_ARGS__)
#define FE_53__(WHAT, X, ...) WHAT(X)FE_52__(WHAT, __VA_ARGS__)
#define FE_54__(WHAT, X, ...) WHAT(X)FE_53__(WHAT, __VA_ARGS__)
#define FE_55__(WHAT, X, ...) WHAT(X)FE_54__(WHAT, __VA_ARGS__)
#define FE_56__(WHAT, X, ...) WHAT(X)FE_55__(WHAT, __VA_ARGS__)
#define FE_57__(WHAT, X, ...) WHAT(X)FE_56__(WHAT, __VA_ARGS__)
#define FE_58__(WHAT, X, ...) WHAT(X)FE_57__(WHAT, __VA_ARGS__)
#define FE_59__(WHAT, X, ...) WHAT(X)FE_58__(WHAT, __VA_ARGS__)
#define FE_60__(WHAT, X, ...) WHAT(X)FE_59__(WHAT, __VA_ARGS__)
#define FE_61__(WHAT, X, ...) WHAT(X)FE_60__(WHAT, __VA_ARGS__)
#define FE_62__(WHAT, X, ...) WHAT(X)FE_61__(WHAT, __VA_ARGS__)
#define FE_63__(WHAT, X, ...) WHAT(X)FE_62__(WHAT, __VA_ARGS__)
#define FE_64__(WHAT, X, ...) WHAT(X)FE_63__(WHAT, __VA_ARGS__)
#define FE_65__(WHAT, X, ...) WHAT(X)FE_64__(WHAT, __VA_ARGS__)
#define FE_66__(WHAT, X, ...) WHAT(X)FE_65__(WHAT, __VA_ARGS__)
#define FE_67__(WHAT, X, ...) WHAT(X)FE_66__(WHAT, __VA_ARGS__)
#define FE_68__(WHAT, X, ...) WHAT(X)FE_67__(WHAT, __VA_ARGS__)
#define FE_69__(WHAT, X, ...) WHAT(X)FE_68__(WHAT, __VA_ARGS__)
#define FE_70__(WHAT, X, ...) WHAT(X)FE_69__(WHAT, __VA_ARGS__)
#define FE_71__(WHAT, X, ...) WHAT(X)FE_70__(WHAT, __VA_ARGS__)
#define FE_72__(WHAT, X, ...) WHAT(X)FE_71__(WHAT, __VA_ARGS__)
#define FE_73__(WHAT, X, ...) WHAT(X)FE_72__(WHAT, __VA_ARGS__)
#define FE_74__(WHAT, X, ...) WHAT(X)FE_73__(WHAT, __VA_ARGS__)
#define FE_75__(WHAT, X, ...) WHAT(X)FE_74__(WHAT, __VA_ARGS__)
#define FE_76__(WHAT, X, ...) WHAT(X)FE_75__(WHAT, __VA_ARGS__)
#define FE_77__(WHAT, X, ...) WHAT(X)FE_76__(WHAT, __VA_ARGS__)
#define FE_78__(WHAT, X, ...) WHAT(X)FE_77__(WHAT, __VA_ARGS__)
#define FE_79__(WHAT, X, ...) WHAT(X)FE_78__(WHAT, __VA_ARGS__)
#define FE_80__(WHAT, X, ...) WHAT(X)FE_79__(WHAT, __VA_ARGS__)
#define FE_81__(WHAT, X, ...) WHAT(X)FE_80__(WHAT, __VA_ARGS__)
#define FE_82__(WHAT, X, ...) WHAT(X)FE_81__(WHAT, __VA_ARGS__)
#define FE_83__(WHAT, X, ...) WHAT(X)FE_82__(WHAT, __VA_ARGS__)
#define FE_84__(WHAT, X, ...) WHAT(X)FE_83__(WHAT, __VA_ARGS__)
#define FE_85__(WHAT, X, ...) WHAT(X)FE_84__(WHAT, __VA_ARGS__)
#define FE_86__(WHAT, X, ...) WHAT(X)FE_85__(WHAT, __VA_ARGS__)
#define FE_87__(WHAT, X, ...) WHAT(X)FE_86__(WHAT, __VA_ARGS__)
#define FE_88__(WHAT, X, ...) WHAT(X)FE_87__(WHAT, __VA_ARGS__)
#define FE_89__(WHAT, X, ...) WHAT(X)FE_88__(WHAT, __VA_ARGS__)
#define FE_90__(WHAT, X, ...) WHAT(X)FE_89__(WHAT, __VA_ARGS__)
#define FE_91__(WHAT, X, ...) WHAT(X)FE_90__(WHAT, __VA_ARGS__)
#define FE_92__(WHAT, X, ...) WHAT(X)FE_91__(WHAT, __VA_ARGS__)
#define FE_93__(WHAT, X, ...) WHAT(X)FE_92__(WHAT, __VA_ARGS__)
#define FE_94__(WHAT, X, ...) WHAT(X)FE_93__(WHAT, __VA_ARGS__)
#define FE_95__(WHAT, X, ...) WHAT(X)FE_94__(WHAT, __VA_ARGS__)
#define FE_96__(WHAT, X, ...) WHAT(X)FE_95__(WHAT, __VA_ARGS__)
#define FE_97__(WHAT, X, ...) WHAT(X)FE_96__(WHAT, __VA_ARGS__)
#define FE_98__(WHAT, X, ...) WHAT(X)FE_97__(WHAT, __VA_ARGS__)
#define FE_99__(WHAT, X, ...) WHAT(X)FE_98__(WHAT, __VA_ARGS__)
#define FE_100__(WHAT, X, ...) WHAT(X)FE_99__(WHAT, __VA_ARGS__)

#define ENUM_STRING(name) #name,

#define FOR_EACH__(action,...) \
  GET_MACRO(__VA_ARGS__,FE_100__,FE_99__,FE_98__,FE_97__,FE_96__,FE_95__,FE_94__,FE_93__,FE_92__,FE_91__,FE_90__,FE_89__,FE_88__,FE_87__,FE_86__,FE_85__,FE_84__,FE_83__,FE_82__,FE_81__,FE_80__,FE_79__,FE_78__,FE_77__,FE_76__,FE_75__,FE_74__,FE_73__,FE_72__,FE_71__,FE_70__,FE_69__,FE_68__,FE_67__,FE_66__,FE_65__,FE_64__,FE_63__,FE_62__,FE_61__,FE_60__,FE_59__,FE_58__,FE_57__,FE_56__,FE_55__,FE_54__,FE_53__,FE_52__,FE_51__,FE_50__,FE_49__,FE_48__,FE_47__,FE_46__,FE_45__,FE_44__,FE_43__,FE_42__,FE_41__,FE_40__,FE_39__,FE_38__,FE_37__,FE_36__,FE_35__,FE_34__,FE_33__,FE_32__,FE_31__,FE_30__,FE_29__,FE_28__,FE_27__,FE_26__,FE_25__,FE_24__,FE_23__,FE_22__,FE_21__,FE_20__,FE_19__,FE_18__,FE_17__,FE_16__,FE_15__,FE_14__,FE_13__,FE_12__,FE_11__,FE_10__,FE_9__,FE_8__,FE_7__,FE_6__,FE_5__,FE_4__,FE_3__,FE_2__,FE_1__)(action,__VA_ARGS__)

#define ENUM(name, ...) typedef enum {__VA_ARGS__} name; \
                        static char* name##_STR[] = {FOR_EACH__(ENUM_STRING, __VA_ARGS__)}

#endif //_ENUM_H_ 
